In [13]:
import pandas as pd
from pathlib import Path
import hvplot.pandas
%matplotlib inline

In [14]:
draft_df = pd.read_csv(Path('./draft-data-20-years.csv'),
                       index_col = 'DraftYear', 
                       parse_dates=False, 
                       infer_datetime_format=True
)

In [15]:
draft_df.head()

,Unnamed: 0,Rk,Pk,Tm,Player,College,Yrs,G,TOTMP,TOTPTS,...,WS,WS/48,BPM,VORP,DraftYr,MPG,PPG,RPG,APG,playerurl
DraftYear,,,,,,,,,,,,,,,,,,,,,
1990,1,1,1,BRK,Derrick Coleman,Syracuse,15.0,781.0,25903.0,12884.0,...,64.3,0.119,1.4,22.3,1990,33.2,16.5,9.3,2.5,https://www.sports-reference.com/cbb/players/d...
1990,2,2,2,OKC,Gary Payton,Oregon State,17.0,1335.0,47117.0,21813.0,...,145.5,0.148,3.3,62.5,1990,35.3,16.3,3.9,6.7,https://www.sports-reference.com/cbb/players/g...
1990,3,3,3,DEN,Mahmoud Abdul-Rauf,LSU,9.0,586.0,15628.0,8553.0,...,25.2,0.077,-0.8,4.5,1990,26.7,14.6,1.9,3.5,https://www.sports-reference.com/cbb/players/m...
1990,4,4,4,ORL,Dennis Scott,Georgia Tech,10.0,629.0,17983.0,8094.0,...,33.4,0.089,0.2,9.9,1990,28.6,12.9,2.8,2.1,https://www.sports-reference.com/cbb/players/d...
1990,5,5,5,CHA,Kendall Gill,Illinois,15.0,966.0,29481.0,12914.0,...,47.8,0.078,0.1,15.8,1990,30.5,13.4,4.1,3.0,https://www.sports-reference.com/cbb/players/k...

In [16]:
draft_df = draft_df[['Rk','Pk','Tm','Player','College','DraftYr','G','TOTPTS', 'TOTTRB', 'TOTAST', 'PPG']]

In [17]:
last_5_yrs_draft_df = draft_df.loc[draft_df['DraftYr'] >= 2017]

In [18]:
last_5_yrs_1_rnd_draft_df = last_5_yrs_draft_df.loc[last_5_yrs_draft_df['Pk'] <=30]

In [19]:
group_a_df = last_5_yrs_1_rnd_draft_df.loc[last_5_yrs_1_rnd_draft_df['Pk'] <=5]
group_a_df.head()

,Rk,Pk,Tm,Player,College,DraftYr,G,TOTPTS,TOTTRB,TOTAST,PPG
DraftYear,,,,,,,,,,,
2017,1,1,PHI,Markelle Fultz,Washington,2017,113.0,1228.0,376.0,524.0,10.9
2017,2,2,LAL,Lonzo Ball,UCLA,2017,252.0,2995.0,1447.0,1563.0,11.9
2017,3,3,BOS,Jayson Tatum,Duke,2017,345.0,7033.0,2280.0,1005.0,20.4
2017,4,4,PHO,Josh Jackson,Kansas,2017,280.0,3224.0,1141.0,529.0,11.5
2017,5,5,SAC,De'Aaron Fox,Kentucky,2017,311.0,5826.0,1094.0,1922.0,18.7

In [8]:
group_b_df = last_5_yrs_1_rnd_draft_df.loc[(last_5_yrs_1_rnd_draft_df['Pk'] >=13) & (last_5_yrs_1_rnd_draft_df['Pk'] <=17)]

In [9]:
group_c_df = last_5_yrs_1_rnd_draft_df.loc[last_5_yrs_1_rnd_draft_df['Pk'] >=26]

In [10]:
group_a_ave=group_a_df.groupby('DraftYear').mean().sort_values('DraftYear')

In [47]:
group_a_ave

            Rk   Pk  DraftYr      G  TOTPTS  TOTTRB  TOTAST    PPG
DraftYear
2017       3.0  3.0   2017.0  260.2  4061.2  1267.6  1108.6  14.68
2018       3.0  3.0   2018.0  210.0  4224.0  1482.2   985.6  19.24
2019       3.0  3.0   2019.0  142.6  2576.4   646.0   630.8  18.46
2020       3.0  3.0   2020.0   90.8  1316.6   434.2   289.8  13.66
2021       3.0  3.0   2021.0   45.0   652.0   257.8   157.8  14.44

In [50]:
group_a_ttl_g_plot = group_a_ave['G'].hvplot(
    title='Average 1st Round Picks Total Games Played 2017-2021',
    x='DraftYear',
    y='G',
    xlabel='Draft Year',
    ylabel='Total Games Played',
    label='Group-A'
)

In [51]:
group_b_ave=group_b_df.groupby('DraftYear').mean().sort_values('DraftYear')

In [52]:
group_b_ave

             Rk    Pk  DraftYr      G  TOTPTS  TOTTRB  TOTAST    PPG
DraftYear
2017       15.0  15.0   2017.0  213.4  2850.0  1025.2   588.6  10.30
2018       15.0  15.0   2018.0  126.6  1050.0   525.0   209.4   7.54
2019       15.0  15.0   2019.0  116.8  1105.4   392.4   220.8   8.60
2020       15.0  15.0   2020.0   92.6   763.0   412.6   186.6   8.14
2021       15.0  15.0   2021.0   45.6   347.4   142.8    63.2   7.20

In [53]:
group_b_ttl_g_plot = group_b_ave['G'].hvplot(
    title='Average 1st Round Picks Total Games Played 2017-2021',
    x='DraftYear',
    y='G',
    xlabel='Draft Year',
    ylabel='Total Games Played',
    label='Group-B'
)

In [54]:
group_c_ave=group_c_df.groupby('DraftYear').mean().sort_values('DraftYear')

In [55]:
group_c_ave

             Rk    Pk  DraftYr      G  TOTPTS  TOTTRB  TOTAST   PPG
DraftYear
2017       28.0  28.0   2017.0  218.0  2308.2  1078.8   467.2  8.72
2018       28.0  28.0   2018.0  120.2   849.8   405.2   160.0  5.96
2019       28.0  28.0   2019.0  107.2  1147.0   365.4   249.0  9.00
2020       28.0  28.0   2020.0   93.8   765.8   279.4   154.6  7.16
2021       28.0  28.0   2021.0   30.6   229.4    93.8    36.8  5.80

In [56]:
group_c_ttl_g_plot = group_c_ave['G'].hvplot(
    title='Average 1st Round Picks Total Games Played 2017-2021',
    x='DraftYear',
    y='G',
    xlabel='Draft Year',
    ylabel='Total Games Played',
    label='Group-C'
)

In [57]:
group_a_ttl_g_plot *group_b_ttl_g_plot * group_c_ttl_g_plot

:Overlay
   .Curve.Group_hyphen_minus_A :Curve   [DraftYear]   (G)
   .Curve.Group_hyphen_minus_B :Curve   [DraftYear]   (G)
   .Curve.Group_hyphen_minus_C :Curve   [DraftYear]   (G)